### ISSUE TITLE
incompatible with unloadtab

### ISSUE THREAD

**Issue by syliew** [Quicksaver/FindBar-Tweak#216]
specifically, when a tab has been loaded after being unloaded by the [UnloadTab](https://addons.mozilla.org/en-US/firefox/addon/unloadtab/) addon and probably others like it, the find fuction simply stops working, it won't highlight any words even though they very clearly are on the page.

also, this issue did not exist prior to verion 2 of fbt.

**Comment by Quicksaver** [comment]
That should be fixed in the next release, thanks for letting me know.

Would you mind trying beta version 2.0.4b1 (https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.0.4b1) which includes this fix, and let me know if it works for you?

**Comment by syliew** [comment]
it works, but your fix created another issue. when a tab has been unloaded the tab title changes to "New Tab" instead of the actual title.

**Comment by Quicksaver** [comment]
So it does...

**Comment by Quicksaver** [comment]
Beta version 2.0.5b1 should help with that: https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.0.5b1

**Comment by syliew** [comment]
the first bug still exists when using [Auto Unload Tab](https://addons.mozilla.org/en-US/firefox/addon/auto-unload-tab/), but still works fine with [UnloadTab](https://addons.mozilla.org/en-US/firefox/addon/unloadtab/). is it possible to fix this issue for all extensions of this type, or is it specific to each one?

**Comment by Quicksaver** [comment]
Unloading a tab is not a native function of Firefox. Any add-on that does it must implement its own method to do it, which means FBT doesn't have anything "general" to follow and react to when this happens, so fixes have to be specific.

Fortunately it's not a difficult thing to do. :) Care to try beta version 2.1.2b1 at https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.2b1 ?

**Comment by syliew** [comment]
it works, thanks.
